# -*- coding: utf-8 -*-
"""Model_test_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMIK7XVnmRA9-XqsvJLyC7a91_4Qi_Y7
"""

import os
import json
import torch
import torch.nn as nn
from torchvision import transforms
from efficientnet_pytorch import EfficientNet
from PIL import Image
import torch.nn.functional as F
import pandas as pd

# DEVICE
device = "cuda" if torch.cuda.is_available() else "cpu"


# LOAD MAIN & SUB CLASSES FROM CSV
df = pd.read_csv("mushroom_structure.csv")

# Main class list
MAIN_CLASSES = df["main_class"].unique().tolist()

# Sub class list
sub_classes = df["sub_class"].unique().tolist()

print("Main Classes:", MAIN_CLASSES)
print("Total Sub Classes:", len(sub_classes))

# MODEL DEFINITION
class HierarchicalEffNetB3(nn.Module):
    def __init__(self, num_main, num_sub):
        super().__init__()
        self.backbone = EfficientNet.from_pretrained('efficientnet-b3')

        in_features = self.backbone._fc.in_features
        self.backbone._fc = nn.Identity()

        self.main_head = nn.Linear(in_features, num_main)
        self.sub_head  = nn.Linear(in_features, num_sub)

    def forward(self, x):
        feat = self.backbone(x)
        return self.main_head(feat), self.sub_head(feat)

# LOAD MODEL
model = HierarchicalEffNetB3(
    num_main=len(MAIN_CLASSES),
    num_sub=len(sub_classes)
).to(device)

model.load_state_dict(
    torch.load("best_hierarchical_effnet_b3.pth", map_location=device)
)
model.eval()

print(" Model loaded successfully")

# TRANSFORMS
tfm = transforms.Compose([
    transforms.Resize(320),
    transforms.CenterCrop(300),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
])

# PREDICT FUNCTION
def predict(img_path):
    img = Image.open(img_path).convert("RGB")
    x = tfm(img).unsqueeze(0).to(device)

    with torch.no_grad():
        main_out, sub_out = model(x)

        main_probs = F.softmax(main_out, dim=1)
        sub_probs  = F.softmax(sub_out, dim=1)

        main_prob, main_idx = torch.max(main_probs, 1)
        sub_prob,  sub_idx  = torch.max(sub_probs, 1)

        result = {
            "Main Class": MAIN_CLASSES[main_idx.item()],
            "Main Confidence (%)": round(main_prob.item() * 100, 2),
            "Species": sub_classes[sub_idx.item()],
            "Species Confidence (%)": round(sub_prob.item() * 100, 2)
        }

        return result

# TEST ON YOUR IMAGE
image_path = "image.jpg"

result = predict(image_path)

print("\n PREDICTION RESULT:")
for k, v in result.items():
    print(f"{k}: {v}")

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

!pip install efficientnet_pytorch

